=== kenyonchristie/SR-XSLT-AI/Senior_Project_Dev_Baseline/Script_3/Script_3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="content">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="description">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="levelledPara"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="levelledPara">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element maxOccurs="unbounded" ref="para"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="para">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="sequentialList"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sequentialList">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="listItem"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="listItem">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="para"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== kenyonchristie/SR-XSLT-AI/Corrected_Files_with_Final_Outputs/Senior_Project_NotionAI/Script_3/Script_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Script_3.xsd">
    <description>
        <levelledPara id="lp-0001">
            <title>DAWN SCIENCE OBJECTIVES</title>
            <!--DEVELOPER INTERVENTION TO ADD MISSING TITLE AND REMOVE EXTRA LEVELLEDPARA ENTRIES THROUGHOUT-->
            <para>To achieve the overall goal of the Dawn mission, a set of science objectives has
                been established that can be met by the instrument suite. These objectives are
                listed below.</para>
            <!--DEVELOPER INTERVENTION TO MOVE CLOSING PARA PRECEDING SEQUENTIAL LIST TO AFTER SEQUENTIAL LIST AND TO ADD PARA CHILDREN TO LISTITMES, THROUGHOUT DOC-->
            <para>The objectives primarily answered by the framing cameras are: <sequentialList
                    id="seq-0001">
                    <listItem>
                        <para>To determine the origin and evolution of Vesta and Ceres by mapping
                            the extent of geologic processes on the asteroid surfaces, and by using
                            the cratering record to establish a relative chronology of the crustal
                            units and population of impactors in the early solar system</para>
                    </listItem>
                    <listItem>
                        <para>To map the shape, determine the spin state, and establish the degree
                            of cratering of the asteroids visited</para>
                    </listItem>
                    <listItem>
                        <para>To map the topography of Vesta and Ceres</para>
                    </listItem>
                    <listItem>
                        <para>To search for dust and satellites in the environment of the asteroids
                            visited</para>
                    </listItem>
                </sequentialList>
            </para>
            <para>The framing cameras will also contribute to answering some of the broader
                objectives: <sequentialList id="seq-0002">
                    <listItem>
                        <para>To provide a geologic, compositional, and geophysical context for the
                            Howardite-EucriteDiogenite (HED) meteorites.</para>
                    </listItem>
                    <listItem>
                        <para>To provide an opportunity to identify Ceres-derived meteorites in
                            their geologic context.</para>
                    </listItem>
                </sequentialList>
            </para>
            <para>The visible and infrared spectrometer scientific objectives are: <sequentialList
                    id="seq-0003">
                    <listItem>
                        <para>To provide a geologic, compositional, and geophysical context for HED
                            meteorites</para>
                    </listItem>
                    <listItem>
                        <para>To provide an opportunity to identify Ceres-derived meteorites in
                            their geologic context</para>
                    </listItem>
                    <listItem>
                        <para>To map the thermophysical properties of Vesta and Ceres</para>
                    </listItem>
                    <listItem>
                        <para>To determine the origin and evolution of Vesta and Ceres by mapping
                            the mineralogical composition and its spatial variation across the
                            asteroidal surface</para>
                    </listItem>
                </sequentialList>
            </para>
            <para>The gamma ray and neutron spectrometer scientific objectives are: <sequentialList
                    id="seq-0004">
                    <listItem>
                        <para>To map the major elemental composition of O, Si, Fe, Mg, Ti, Al, Ca,
                            and H on Vesta and Ceres</para>
                    </listItem>
                    <listItem>
                        <para>To map the trace elements U, Th, K, Gd, and Sm on Vesta and
                            Ceres</para>
                    </listItem>
                    <listItem>
                        <para>To provide a geologic, compositional, and geophysical context for the
                            HED meteorites</para>
                    </listItem>
                </sequentialList>
            </para>
            <para>The gravity science scientific objectives are: <sequentialList id="seq-0005">
                    <listItem>
                        <para>To determine the masses of the asteroids visited</para>
                    </listItem>
                    <listItem>
                        <para>To measure the bulk density of Vesta and Ceres, in conjunction with
                            topography, and determine heterogeneity</para>
                    </listItem>
                    <listItem>
                        <para>To determine the gravitational fields of Vesta and Ceres</para>
                    </listItem>
                </sequentialList>
            </para>
        </levelledPara>
    </description>
</content>
